/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a2' at '9/2/16 8:21 PM' with Gradle 2.13
 *
 * @author a2, @date 9/2/16 8:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
